server:
  port: 7002
  servlet:
    context-path: /nacos


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.1:8801,192.168.11.1:88013,192.168.11.1:8805
  application:
    name: service-provider

